# Configure postfix
---
- name: Install postix main.cf 
  copy:
    src: ../files/etc/postfix/main.cf
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify: restart Postfix

# Deploy master.cf
- name: Deploy postfix conf
  copy:
    src: ../files/etc/postfix/master.cf
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: 0644
  notify: restart Postfix

# Deploy policyd-spf.conf
- name: Deploy postfix spf
  copy:
    src: ../files/etc/postfix-policyd-spf-python/policyd-spf.conf
    dest: /etc/postfix-policyd-spf-python/policyd-spf.conf
    owner: root
    group: root
    mode: 0644

# Deploy cron for reports
- name: Deploy cron reports
  copy:
    src: ../files/etc/cron.daily/postfix_stats
    dest: /etc/cron.daily/postfix_stats
    owner: root
    group: root
    mode: 0755
