# Configure UFW rules
---
- name: Create UFW tcp rules 
  ufw:
    rule: allow
    proto: tcp
    port: '{{ item }}'
  with_items:
    - '70'
    - '79'
    - '80'
    - '113'
    - '143'
    - '443'
    - '1326'
    - '5154'
    - '6697'
    - '7776'
    - '30000'
    - '25565' 

- name: Create UFW udp rules
  ufw:
    rule: allow
    proto: udp
    port: '{{ item }}'
  with_items:
      - '60000:61000'
      - '1326'
      - '5154'
      - '30000'

- name: Create tcp limits
  ufw:
    rule: limit
    proto: tcp
    port: '{{ item }}'
  with_items:
    - '22'
    - '25'
    - '587'
    - '2222'
    - '53'

- name: Create UDP limits
  ufw:
    rule: limit
    proto: udp
    port: '{{ item }}'
  with_items:
    - '53'
