---
# This is the overall site playbook.
- name: Baseline Configuration 
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - common

- name: Shell server cofiguration
  hosts: shell
  become: yes
  become_method: sudo

  roles:
    - shell

#- name: Web server configuration
#  hosts: webserver
#  become: yes
#  become_method: sudo

#  roles:
#    - webserver
