#!/bin/bash
export RUNNING="/dev/shm/ansible_is_running"

if [ -f $RUNNING ]; then
   echo "Ansible is currently running."
	exit 1
else
	touch $RUNNING
	cd /var/tilde/ansible
	/usr/bin/git pull
	/usr/local/bin/ansible-playbook -i /var/tilde/ansible/hosts_local /var/tilde/ansible/site.yml -u root
	touch /dev/shm/ansible-hook-last-run
	rm $RUNNING
	exit 0
fi
