#- name: Add ansible cron job
#  copy:
#    src: ../files/ansible-pull
#    dest: /etc/cron.hourly/ansible-pull
#    owner: root
#    mode: 0755
#    state: absent

- name: Add githook local script
  copy:
    src: ../files/ansible-run
    dest: /usr/local/bin/ansible-run
    owner: root
    mode: 0755

- name: Add githook systemd path unit
  copy:
    src: ../files/ansible-run.path
    dest: /etc/systemd/system/ansible-run.path
    owner: root
    group: root
    mode: 0644

- name: Add githook system service unit
  copy:
    src: ../files/ansible-run.service
    dest: /etc/systemd/system/ansible-run.service
    owner: root
    group: root
    mode: 0644

- name: Enabling ansible-pull units
  systemd:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - 'ansible-run.path'
    - 'ansible-run.service'

#- name: Add mirror rsync cron job
#  copy:
#    src: ../files/mirror-rsync
#    dest: /etc/cron.hourly/mirror-rsync
#    owner: root
#    mode: 0775
    
#- name: Add mirror rsync cron job (daily)
#  copy:
#    src: ../files/mirror-rsync-daily
#    dest: /etc/cron.daily/mirror-rsync-daily
#    owner: root
#    mode: 0775
    
- name: Adding ansible git repo locally
  git:
    repo: 'https://github.com/hackclub-tilde/ansible.git'
    dest: /var/tilde/ansible
   
