# This will set our resolvers up, to the .tilde tld name servers.
---
- name: Set system resolvers
  copy:
    src: ../files/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
