# Configure apache2
---

# Certbot
- name: Add certbot cron job
  copy:
    src: ../files/certbot-renew
    dest: /etc/cron.weekly/certbot-renew
    owner: root
    mode: 755

# Sites
- name: Deploy Apache2 site configs
  copy:
    src: ../files/etc/apache2/sites-available/{{ item }}.conf
    dest: /etc/apache2/sites-available/{{ item }}.conf
  loop:
    - default-ssl
    - thunix.cf
    - www.thunix.cf
    - ftp.thunix.cf
    - thunix.net
    - www.thunix.net
    - ftp.thunix.net
    - staticadventures.netlib.re
    - deb.thunix.net
    - rpm.thunix.net
    - stats.thunix.net
    - wiki.thunix.net
    - lukewarmcat.codes
    - xerty.lukewarmcat.codes
    - mightywcms.thunix.net
      
- name: Make Apache2 site configs live 
  file:
    src: /etc/apache2/sites-available/{{ item }}.conf
    dest: /etc/apache2/sites-enabled/{{ item }}.conf
    state: link
  loop:
    - default-ssl
    - thunix.cf
    - www.thunix.cf
    - ftp.thunix.cf
    - thunix.net
    - www.thunix.net
    - ftp.thunix.net
    - staticadventures.netlib.re
    - deb.thunix.net
    - rpm.thunix.net
    - stats.thunix.net
    - wiki.thunix.net
    - lukewarmcat.codes
    - xerty.lukewarmcat.codes
    - mightywcms.thunix.net

- name: Give permissions for staticadventures.netlib.re to southerntofu
  file:
    path: /var/www/staticadventures.netlib.re
    state: directory
    owner: southerntofu
    group: southerntofu
    recurse: yes # Can be removed in the future, but for now all files still have old uid/gid
