# Install apache and accoutrements www, irrespective of what role they might have
---
- name: Add apt key for tor project repo
  apt_key:
    url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
    state: present

- name: Add tor project repo
  apt_repository:
    repo: 'deb https://deb.torproject.org/torproject.org bullseye main'
    state: present
    filename: tor
    update_cache: yes

- name: Add tor project repo
  apt_repository:
    repo: 'deb-src https://deb.torproject.org/torproject.org bullseye main'
    state: present
    filename: torsrc
    update_cache: yes

- name: Install packages for webserver
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apache2
#      - createrepo
      - dpkg-dev
#      - gophernicus
      - mariadb-client
      - mariadb-server
      - php-imagick
      - php-mbstring
      - php-memcache
      - php-pear
      - php
      - php-curl
      - php-gd
      - php-imap
      - php-intl
      - php-mysql
      - php-pspell
#      - php-recode
      - php-sqlite3
      - php-tidy
      - php-xmlrpc
#      - php7.3-xsl
      - tor
      - torsocks
#      - yum-utils
