# This creates our users on the system
---
- group:
    name: sudo
    state: present

- user:
    name: muirrum
    groups: sudo,tilde
    state: present
    skeleton: /etc/skel
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/ubergeek
